// **NOTE**: this file is generated by `dhall-render`.
// You should NOT edit it manually, your changes will be lost.

ThisBuild / scalaVersion := "2.13.7"
ThisBuild / organization := "net.gfxmonk"
ThisBuild / homepage := Some(url(s"https://github.com/timbertson/foperator"))
ThisBuild / scmInfo := Some(
  ScmInfo(
    url("https://github.com/timbertson/foperator"),
    s"scm:git@github.com:timbertson/foperator.git"
  )
)
import scala.util.Try

ThisBuild / version := Try(IO.read(new File("VERSION")).trim()).getOrElse("0.0.0-SNAPSHOT")
ThisBuild / versionScheme := Some("early-semver")

sonatypeProfileName := "net.gfxmonk"

credentials += Credentials(
  "Sonatype Nexus Repository Manager",
  "oss.sonatype.org",
  "timbertson",
  sys.env.getOrElse("SONATYPE_PASSWORD", "******"))

ThisBuild / licenses := Seq("MIT" -> url("http://www.opensource.org/licenses/mit-license.php"))

ThisBuild / developers := List(
  Developer(
    id    = "gfxmonk",
    name  = "Tim Cuthbertson",
    email = "tim@gfxmonk.net",
    url   = url("http://gfxmonk.net")
  )
)

