// NOTE: This file is generated by chored

import sbt._
import Keys._
import xerial.sbt.Sonatype.SonatypeKeys._

object ScalaProject {
	val hiddenProjectSettings = Seq(
		publish / skip := true,
		publishTo := None,
	)

	def publicProjectSettings = Seq(
		publishTo := sonatypePublishToBundle.value,
		publishMavenStyle := true,
		Test / publishArtifact := false,
	)

	val scala2Version = "2.13.14"
	val scala3Version = "3.4.2"
}
