# permissions for end users to edit greetings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greeting-editor-role
rules:
- apiGroups:
  - sample.foperator.gfxmonk.net
  resources:
  - greetings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.foperator.gfxmonk.net
  resources:
  - greetings/status
  verbs:
  - get
