# permissions for end users to edit people.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: person-editor-role
rules:
- apiGroups:
  - sample.foperator.gfxmonk.net
  resources:
  - people
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.foperator.gfxmonk.net
  resources:
  - people/status
  verbs:
  - get
